/* Auto-generated ESPN team lookup — no API key required */
const ESPN_TEAM_DB = [
  {id:"6418",league:"ger.1",name:"1. FC Heidenheim 1846",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/6418.png"},
  {id:"598",league:"ger.1",name:"1. FC Union Berlin",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/598.png"},
  {id:"103",league:"ita.1",name:"AC Milan",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/103.png"},
  {id:"349",league:"eng.1",name:"AFC Bournemouth",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/349.png"},
  {id:"172",league:"fra.1",name:"AJ Auxerre",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/172.png"},
  {id:"174",league:"fra.1",name:"AS Monaco",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/174.png"},
  {id:"104",league:"ita.1",name:"AS Roma",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/104.png"},
  {id:"22064",league:"por.1",name:"AVS",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/22064.png"},
  {id:"140",league:"ned.1",name:"AZ Alkmaar",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/140.png"},
  {id:"263",league:"sco.1",name:"Aberdeen",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/263.png"},
  {id:"139",league:"ned.1",name:"Ajax Amsterdam",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/139.png"},
  {id:"9078",league:"tur.1",name:"Alanyaspor",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/9078.png"},
  {id:"96",league:"esp.1",name:"Alav\u00e9s",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/96.png"},
  {id:"21613",league:"por.1",name:"Alverca",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/21613.png"},
  {id:"7868",league:"fra.1",name:"Angers",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/7868.png"},
  {id:"3794",league:"tur.1",name:"Antalyaspor",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/3794.png"},
  {id:"15784",league:"por.1",name:"Arouca",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/15784.png"},
  {id:"359",league:"eng.1",name:"Arsenal",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/359.png"},
  {id:"362",league:"eng.1",name:"Aston Villa",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/362.png"},
  {id:"105",league:"ita.1",name:"Atalanta",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/105.png"},
  {id:"93",league:"esp.1",name:"Athletic Club",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/93.png"},
  {id:"3458",league:"bra.1",name:"Athletico-PR",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/3458.png"},
  {id:"18418",league:"usa.1",name:"Atlanta United FC",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/18418.png"},
  {id:"1068",league:"esp.1",name:"Atl\u00e9tico Madrid",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/1068.png"},
  {id:"7632",league:"bra.1",name:"Atl\u00e9tico-MG",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/7632.png"},
  {id:"20906",league:"usa.1",name:"Austin FC",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/20906.png"},
  {id:"9967",league:"bra.1",name:"Bahia",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/9967.png"},
  {id:"83",league:"esp.1",name:"Barcelona",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/83.png"},
  {id:"131",league:"ger.1",name:"Bayer Leverkusen",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/131.png"},
  {id:"132",league:"ger.1",name:"Bayern Munich",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/132.png"},
  {id:"1929",league:"por.1",name:"Benfica",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/1929.png"},
  {id:"1895",league:"tur.1",name:"Besiktas",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/1895.png"},
  {id:"392",league:"eng.2",name:"Birmingham City",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/392.png"},
  {id:"365",league:"eng.2",name:"Blackburn Rovers",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/365.png"},
  {id:"2980",league:"UEFA.CHAMPIONS",name:"Bodo/Glimt",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/2980.png"},
  {id:"107",league:"ita.1",name:"Bologna",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/107.png"},
  {id:"124",league:"ger.1",name:"Borussia Dortmund",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/124.png"},
  {id:"268",league:"ger.1",name:"Borussia M\u00f6nchengladbach",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/268.png"},
  {id:"6086",league:"bra.1",name:"Botafogo",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/6086.png"},
  {id:"2994",league:"por.1",name:"Braga",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/2994.png"},
  {id:"337",league:"eng.1",name:"Brentford",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/337.png"},
  {id:"6997",league:"fra.1",name:"Brest",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/6997.png"},
  {id:"331",league:"eng.1",name:"Brighton & Hove Albion",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/331.png"},
  {id:"333",league:"eng.2",name:"Bristol City",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/333.png"},
  {id:"379",league:"eng.1",name:"Burnley",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/379.png"},
  {id:"3472",league:"por.1",name:"C.D. Nacional",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/3472.png"},
  {id:"9720",league:"usa.1",name:"CF Montr\u00e9al",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/9720.png"},
  {id:"2925",league:"ita.1",name:"Cagliari",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/2925.png"},
  {id:"21581",league:"por.1",name:"Casa Pia",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/21581.png"},
  {id:"7656",league:"tur.1",name:"Caykur Rizespor",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/7656.png"},
  {id:"85",league:"esp.1",name:"Celta Vigo",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/85.png"},
  {id:"256",league:"sco.1",name:"Celtic",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/256.png"},
  {id:"9318",league:"bra.1",name:"Chapecoense",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/9318.png"},
  {id:"21300",league:"usa.1",name:"Charlotte FC",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/21300.png"},
  {id:"372",league:"eng.2",name:"Charlton Athletic",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/372.png"},
  {id:"363",league:"eng.1",name:"Chelsea",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/363.png"},
  {id:"182",league:"usa.1",name:"Chicago Fire FC",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/182.png"},
  {id:"570",league:"UEFA.CHAMPIONS",name:"Club Brugge",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/570.png"},
  {id:"184",league:"usa.1",name:"Colorado Rapids",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/184.png"},
  {id:"183",league:"usa.1",name:"Columbus Crew",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/183.png"},
  {id:"2572",league:"ita.1",name:"Como",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/2572.png"},
  {id:"874",league:"bra.1",name:"Corinthians",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/874.png"},
  {id:"3456",league:"bra.1",name:"Coritiba",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/3456.png"},
  {id:"388",league:"eng.2",name:"Coventry City",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/388.png"},
  {id:"4050",league:"ita.1",name:"Cremonese",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/4050.png"},
  {id:"2022",league:"bra.1",name:"Cruzeiro",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/2022.png"},
  {id:"384",league:"eng.1",name:"Crystal Palace",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/384.png"},
  {id:"193",league:"usa.1",name:"D.C. United",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/193.png"},
  {id:"374",league:"eng.2",name:"Derby County",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/374.png"},
  {id:"597",league:"UEFA.EUROPA",name:"Dinamo Zagreb",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/597.png"},
  {id:"261",league:"sco.1",name:"Dundee",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/261.png"},
  {id:"264",league:"sco.1",name:"Dundee United",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/264.png"},
  {id:"125",league:"ger.1",name:"Eintracht Frankfurt",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/125.png"},
  {id:"3751",league:"esp.1",name:"Elche",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/3751.png"},
  {id:"88",league:"esp.1",name:"Espanyol",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/88.png"},
  {id:"12216",league:"por.1",name:"Estoril",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/12216.png"},
  {id:"21610",league:"por.1",name:"Estrela",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/21610.png"},
  {id:"368",league:"eng.1",name:"Everton",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/368.png"},
  {id:"2566",league:"ned.1",name:"Excelsior",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/2566.png"},
  {id:"20729",league:"tur.1",name:"Eyupspor",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/20729.png"},
  {id:"909",league:"UEFA.CHAMPIONS",name:"F.C. K\u00f8benhavn",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/909.png"},
  {id:"3841",league:"ger.1",name:"FC Augsburg",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/3841.png"},
  {id:"989",league:"UEFA.EUROPA",name:"FC Basel",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/989.png"},
  {id:"18267",league:"usa.1",name:"FC Cincinnati",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/18267.png"},
  {id:"122",league:"ger.1",name:"FC Cologne",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/122.png"},
  {id:"185",league:"usa.1",name:"FC Dallas",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/185.png"},
  {id:"12698",league:"por.1",name:"FC Famalicao",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/12698.png"},
  {id:"145",league:"ned.1",name:"FC Groningen",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/145.png"},
  {id:"572",league:"UEFA.EUROPA",name:"FC Midtjylland",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/572.png"},
  {id:"437",league:"por.1",name:"FC Porto",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/437.png"},
  {id:"152",league:"ned.1",name:"FC Twente",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/152.png"},
  {id:"153",league:"ned.1",name:"FC Utrecht",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/153.png"},
  {id:"2727",league:"ned.1",name:"FC Volendam",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/2727.png"},
  {id:"484",league:"UEFA.EUROPA",name:"FCSB",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/484.png"},
  {id:"10414",league:"UEFA.CHAMPIONS",name:"FK Qarabag",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/10414.png"},
  {id:"254",league:"sco.1",name:"Falkirk",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/254.png"},
  {id:"20736",league:"tur.1",name:"Fatih Karag\u00fcmr\u00fck",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/20736.png"},
  {id:"436",league:"tur.1",name:"Fenerbahce",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/436.png"},
  {id:"622",league:"UEFA.EUROPA",name:"Ferencvaros",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/622.png"},
  {id:"142",league:"ned.1",name:"Feyenoord Rotterdam",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/142.png"},
  {id:"109",league:"ita.1",name:"Fiorentina",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/109.png"},
  {id:"819",league:"bra.1",name:"Flamengo",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/819.png"},
  {id:"3445",league:"bra.1",name:"Fluminense",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/3445.png"},
  {id:"143",league:"ned.1",name:"Fortuna Sittard",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/143.png"},
  {id:"370",league:"eng.1",name:"Fulham",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/370.png"},
  {id:"432",league:"tur.1",name:"Galatasaray",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/432.png"},
  {id:"20070",league:"tur.1",name:"Gaziantep FK",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/20070.png"},
  {id:"996",league:"tur.1",name:"Genclerbirligi",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/996.png"},
  {id:"3263",league:"ita.1",name:"Genoa",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/3263.png"},
  {id:"2922",league:"esp.1",name:"Getafe",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/2922.png"},
  {id:"3699",league:"por.1",name:"Gil Vicente",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/3699.png"},
  {id:"9812",league:"esp.1",name:"Girona",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/9812.png"},
  {id:"3706",league:"ned.1",name:"Go Ahead Eagles",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/3706.png"},
  {id:"789",league:"tur.1",name:"Goztepe",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/789.png"},
  {id:"6273",league:"bra.1",name:"Gr\u00eamio",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/6273.png"},
  {id:"127",league:"ger.1",name:"Hamburg SV",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/127.png"},
  {id:"262",league:"sco.1",name:"Heart of Midlothian",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/262.png"},
  {id:"146",league:"ned.1",name:"Heerenveen",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/146.png"},
  {id:"119",league:"ita.1",name:"Hellas Verona",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/119.png"},
  {id:"3708",league:"ned.1",name:"Heracles Almelo",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/3708.png"},
  {id:"258",league:"sco.1",name:"Hibernian",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/258.png"},
  {id:"6077",league:"usa.1",name:"Houston Dynamo FC",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/6077.png"},
  {id:"306",league:"eng.2",name:"Hull City",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/306.png"},
  {id:"20232",league:"usa.1",name:"Inter Miami CF",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/20232.png"},
  {id:"1936",league:"bra.1",name:"Internacional",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/1936.png"},
  {id:"110",league:"ita.1",name:"Internazionale",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/110.png"},
  {id:"373",league:"eng.2",name:"Ipswich Town",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/373.png"},
  {id:"7914",league:"tur.1",name:"Istanbul Basaksehir",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/7914.png"},
  {id:"111",league:"ita.1",name:"Juventus",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/111.png"},
  {id:"2528",league:"UEFA.CHAMPIONS",name:"Kairat Almaty",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/2528.png"},
  {id:"6870",league:"tur.1",name:"Kasimpasa",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/6870.png"},
  {id:"3643",league:"tur.1",name:"Kayserispor",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/3643.png"},
  {id:"260",league:"sco.1",name:"Kilmarnock",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/260.png"},
  {id:"995",league:"tur.1",name:"Kocaelispor",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/995.png"},
  {id:"7648",league:"tur.1",name:"Konyaspor",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/7648.png"},
  {id:"187",league:"usa.1",name:"LA Galaxy",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/187.png"},
  {id:"18966",league:"usa.1",name:"LAFC",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/18966.png"},
  {id:"112",league:"ita.1",name:"Lazio",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/112.png"},
  {id:"3236",league:"fra.1",name:"Le Havre AC",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/3236.png"},
  {id:"113",league:"ita.1",name:"Lecce",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/113.png"},
  {id:"357",league:"eng.1",name:"Leeds United",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/357.png"},
  {id:"375",league:"eng.2",name:"Leicester City",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/375.png"},
  {id:"175",league:"fra.1",name:"Lens",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/175.png"},
  {id:"1538",league:"esp.1",name:"Levante",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/1538.png"},
  {id:"166",league:"fra.1",name:"Lille",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/166.png"},
  {id:"364",league:"eng.1",name:"Liverpool",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/364.png"},
  {id:"259",league:"sco.1",name:"Livingston",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/259.png"},
  {id:"273",league:"fra.1",name:"Lorient",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/273.png"},
  {id:"13018",league:"UEFA.EUROPA",name:"Ludogorets Razgrad",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/13018.png"},
  {id:"167",league:"fra.1",name:"Lyon",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/167.png"},
  {id:"524",league:"UEFA.EUROPA",name:"Maccabi Tel-Aviv",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/524.png"},
  {id:"2950",league:"ger.1",name:"Mainz",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/2950.png"},
  {id:"84",league:"esp.1",name:"Mallorca",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/84.png"},
  {id:"2720",league:"UEFA.EUROPA",name:"Malm\u00f6 FF",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/2720.png"},
  {id:"382",league:"eng.1",name:"Manchester City",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/382.png"},
  {id:"360",league:"eng.1",name:"Manchester United",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/360.png"},
  {id:"176",league:"fra.1",name:"Marseille",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/176.png"},
  {id:"177",league:"fra.1",name:"Metz",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/177.png"},
  {id:"369",league:"eng.2",name:"Middlesbrough",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/369.png"},
  {id:"391",league:"eng.2",name:"Millwall",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/391.png"},
  {id:"17362",league:"usa.1",name:"Minnesota United FC",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/17362.png"},
  {id:"9169",league:"bra.1",name:"Mirassol",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/9169.png"},
  {id:"3696",league:"por.1",name:"Moreirense",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/3696.png"},
  {id:"266",league:"sco.1",name:"Motherwell",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/266.png"},
  {id:"141",league:"ned.1",name:"NAC Breda",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/141.png"},
  {id:"147",league:"ned.1",name:"NEC Nijmegen",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/147.png"},
  {id:"165",league:"fra.1",name:"Nantes",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/165.png"},
  {id:"114",league:"ita.1",name:"Napoli",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/114.png"},
  {id:"18986",league:"usa.1",name:"Nashville SC",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/18986.png"},
  {id:"189",league:"usa.1",name:"New England Revolution",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/189.png"},
  {id:"17606",league:"usa.1",name:"New York City FC",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/17606.png"},
  {id:"361",league:"eng.1",name:"Newcastle United",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/361.png"},
  {id:"2502",league:"fra.1",name:"Nice",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/2502.png"},
  {id:"381",league:"eng.2",name:"Norwich City",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/381.png"},
  {id:"393",league:"eng.1",name:"Nottingham Forest",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/393.png"},
  {id:"435",league:"UEFA.CHAMPIONS",name:"Olympiacos",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/435.png"},
  {id:"12011",league:"usa.1",name:"Orlando City SC",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/12011.png"},
  {id:"97",league:"esp.1",name:"Osasuna",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/97.png"},
  {id:"311",league:"eng.2",name:"Oxford United",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/311.png"},
  {id:"605",league:"UEFA.EUROPA",name:"PAOK Salonika",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/605.png"},
  {id:"2565",league:"ned.1",name:"PEC Zwolle",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/2565.png"},
  {id:"148",league:"ned.1",name:"PSV Eindhoven",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/148.png"},
  {id:"22281",league:"UEFA.CHAMPIONS",name:"Pafos",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/22281.png"},
  {id:"2029",league:"bra.1",name:"Palmeiras",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/2029.png"},
  {id:"443",league:"UEFA.EUROPA",name:"Panathinaikos",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/443.png"},
  {id:"6851",league:"fra.1",name:"Paris FC",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/6851.png"},
  {id:"160",league:"fra.1",name:"Paris Saint-Germain",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/160.png"},
  {id:"115",league:"ita.1",name:"Parma",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/115.png"},
  {id:"10739",league:"usa.1",name:"Philadelphia Union",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/10739.png"},
  {id:"3956",league:"ita.1",name:"Pisa",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/3956.png"},
  {id:"9723",league:"usa.1",name:"Portland Timbers",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/9723.png"},
  {id:"385",league:"eng.2",name:"Portsmouth",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/385.png"},
  {id:"394",league:"eng.2",name:"Preston North End",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/394.png"},
  {id:"334",league:"eng.2",name:"Queens Park Rangers",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/334.png"},
  {id:"11420",league:"ger.1",name:"RB Leipzig",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/11420.png"},
  {id:"2790",league:"UEFA.EUROPA",name:"RB Salzburg",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/2790.png"},
  {id:"938",league:"UEFA.EUROPA",name:"Racing Genk",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/938.png"},
  {id:"257",league:"sco.1",name:"Rangers",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/257.png"},
  {id:"101",league:"esp.1",name:"Rayo Vallecano",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/101.png"},
  {id:"244",league:"esp.1",name:"Real Betis",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/244.png"},
  {id:"86",league:"esp.1",name:"Real Madrid",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/86.png"},
  {id:"92",league:"esp.1",name:"Real Oviedo",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/92.png"},
  {id:"4771",league:"usa.1",name:"Real Salt Lake",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/4771.png"},
  {id:"89",league:"esp.1",name:"Real Sociedad",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/89.png"},
  {id:"6079",league:"bra.1",name:"Red Bull Bragantino",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/6079.png"},
  {id:"190",league:"usa.1",name:"Red Bull New York",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/190.png"},
  {id:"2290",league:"UEFA.EUROPA",name:"Red Star Belgrade",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/2290.png"},
  {id:"4936",league:"bra.1",name:"Remo",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/4936.png"},
  {id:"3822",league:"por.1",name:"Rio Ave",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/3822.png"},
  {id:"126",league:"ger.1",name:"SC Freiburg",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/126.png"},
  {id:"620",league:"UEFA.EUROPA",name:"SK Brann",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/620.png"},
  {id:"3746",league:"UEFA.EUROPA",name:"SK Sturm Graz",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/3746.png"},
  {id:"11429",league:"tur.1",name:"Samsunspor",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/11429.png"},
  {id:"22529",league:"usa.1",name:"San Diego FC",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/22529.png"},
  {id:"191",league:"usa.1",name:"San Jose Earthquakes",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/191.png"},
  {id:"12215",league:"por.1",name:"Santa Clara",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/12215.png"},
  {id:"2674",league:"bra.1",name:"Santos",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/2674.png"},
  {id:"3997",league:"ita.1",name:"Sassuolo",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/3997.png"},
  {id:"9726",league:"usa.1",name:"Seattle Sounders FC",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/9726.png"},
  {id:"243",league:"esp.1",name:"Sevilla",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/243.png"},
  {id:"398",league:"eng.2",name:"Sheffield United",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/398.png"},
  {id:"399",league:"eng.2",name:"Sheffield Wednesday",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/399.png"},
  {id:"494",league:"UEFA.CHAMPIONS",name:"Slavia Prague",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/494.png"},
  {id:"376",league:"eng.2",name:"Southampton",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/376.png"},
  {id:"151",league:"ned.1",name:"Sparta Rotterdam",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/151.png"},
  {id:"2250",league:"por.1",name:"Sporting CP",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/2250.png"},
  {id:"186",league:"usa.1",name:"Sporting Kansas City",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/186.png"},
  {id:"250",league:"sco.1",name:"St Mirren",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/250.png"},
  {id:"21812",league:"usa.1",name:"St. Louis CITY SC",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/21812.png"},
  {id:"270",league:"ger.1",name:"St. Pauli",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/270.png"},
  {id:"169",league:"fra.1",name:"Stade Rennais",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/169.png"},
  {id:"336",league:"eng.2",name:"Stoke City",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/336.png"},
  {id:"180",league:"fra.1",name:"Strasbourg",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/180.png"},
  {id:"366",league:"eng.1",name:"Sunderland",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/366.png"},
  {id:"318",league:"eng.2",name:"Swansea City",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/318.png"},
  {id:"2026",league:"bra.1",name:"S\u00e3o Paulo",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/2026.png"},
  {id:"7911",league:"ger.1",name:"TSG Hoffenheim",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/7911.png"},
  {id:"3735",league:"ned.1",name:"Telstar",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/3735.png"},
  {id:"12706",league:"por.1",name:"Tondela",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/12706.png"},
  {id:"239",league:"ita.1",name:"Torino",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/239.png"},
  {id:"7318",league:"usa.1",name:"Toronto FC",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/7318.png"},
  {id:"367",league:"eng.1",name:"Tottenham Hotspur",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/367.png"},
  {id:"179",league:"fra.1",name:"Toulouse",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/179.png"},
  {id:"997",league:"tur.1",name:"Trabzonspor",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/997.png"},
  {id:"118",league:"ita.1",name:"Udinese",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/118.png"},
  {id:"5807",league:"UEFA.CHAMPIONS",name:"Union St.-Gilloise",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/5807.png"},
  {id:"94",league:"esp.1",name:"Valencia",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/94.png"},
  {id:"9727",league:"usa.1",name:"Vancouver Whitecaps",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/9727.png"},
  {id:"3454",league:"bra.1",name:"Vasco da Gama",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/3454.png"},
  {id:"134",league:"ger.1",name:"VfB Stuttgart",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/134.png"},
  {id:"138",league:"ger.1",name:"VfL Wolfsburg",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/138.png"},
  {id:"11706",league:"UEFA.EUROPA",name:"Viktoria Plzen",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/11706.png"},
  {id:"102",league:"esp.1",name:"Villarreal",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/102.png"},
  {id:"3457",league:"bra.1",name:"Vit\u00f3ria",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/3457.png"},
  {id:"5309",league:"por.1",name:"Vit\u00f3ria de Guimaraes",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/5309.png"},
  {id:"395",league:"eng.2",name:"Watford",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/395.png"},
  {id:"137",league:"ger.1",name:"Werder Bremen",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/137.png"},
  {id:"383",league:"eng.2",name:"West Bromwich Albion",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/383.png"},
  {id:"371",league:"eng.1",name:"West Ham United",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/371.png"},
  {id:"380",league:"eng.1",name:"Wolverhampton Wanderers",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/380.png"},
  {id:"352",league:"eng.2",name:"Wrexham",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/352.png"},
  {id:"2722",league:"UEFA.EUROPA",name:"Young Boys",logo:"https://a.espncdn.com/i/teamlogos/soccer/500/2722.png"},
];
